#!/bin/sh
BATTINFO=`acpi -b`

echo "Начинаем..."
while (true) 
do
    if [[ `echo $BATTINFO | grep Discharging` && `echo $BATTINFO | cut -f 5 -d " "` < 00:15:00 ]] ; then
        DISPLAY=:0.0 /usr/bin/notify-send -u critical "Low Battery! Connect charger!" "$BATTINFO"
    fi
    sleep 300; # пауза 5 минут
done;